package org.expenses;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "EXPENSE_REPORT")
public class ExpenseReport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EXPENSEREPORT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "EXPENSEREPORT_ID_SEQ", name = "EXPENSEREPORT_ID_GENERATOR")
   @javax.persistence.Column(unique = true, nullable = false)
   private java.lang.Long id;

   private java.lang.String user;

   private java.util.Date created;

   private java.lang.String status;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL })
   private java.util.List<org.expenses.ExpenseReportLine> lines;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   private java.util.List<java.lang.String> notes;

   public ExpenseReport()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getUser()
   {
      return this.user;
   }

   public void setUser(java.lang.String user)
   {
      this.user = user;
   }

   public java.util.Date getCreated()
   {
      return this.created;
   }

   public void setCreated(java.util.Date created)
   {
      this.created = created;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.util.List<org.expenses.ExpenseReportLine> getLines()
   {
      return this.lines;
   }

   public void setLines(java.util.List<org.expenses.ExpenseReportLine> lines)
   {
      this.lines = lines;
   }

   public java.util.List<java.lang.String> getNotes()
   {
      return this.notes;
   }

   public void setNotes(java.util.List<java.lang.String> notes)
   {
      this.notes = notes;
   }

   public ExpenseReport(java.lang.Long id, java.lang.String user,
         java.util.Date created, java.lang.String status,
         java.util.List<org.expenses.ExpenseReportLine> lines,
         java.util.List<java.lang.String> notes)
   {
      this.id = id;
      this.user = user;
      this.created = created;
      this.status = status;
      this.lines = lines;
      this.notes = notes;
   }

}